[package]
name = "cbor4ii"
version = "0.2.10"
authors = ["quininer <quininer@live.com>"]
description = "CBOR: Concise Binary Object Representation"
repository = "https://github.com/quininer/cbor4ii"
categories = [ "encoding", "no-std" ]
keywords = [ "serde", "cbor", "serialization" ]
license = "MIT"
edition = "2018"

[features]
use_std = [ "serde/std", "use_alloc" ]
use_alloc = []
half-f16 = [ "half" ]
serde1 = [ "serde", "use_alloc" ]

# Deprecated, use serde1 instead
serde1-value = [ "serde1" ]

[dependencies]
cid = { version = "0.8.3", features = ["serde-codec"] }
half = { version = "1", default-features = false, optional = true }
serde = { version = "1", default-features = false, optional = true }

[dev-dependencies]
anyhow = "1"
serde = { version = "1", features = [ "derive" ] }
serde_bytes = "0.11"
data-encoding = "2"
serde_cbor = "0.11"
ciborium = "0.2"
criterion = "0.3"
libipld-core = { version = "0.13.1", features = ["serde-codec"] }
serde_derive = { version = "1.0.14", default-features = false }

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "ser"
path = "benches/bench_ser.rs"
harness = false

[[bench]]
name = "de"
path = "benches/bench_de.rs"
harness = false
